.PHONY: kitex_gen
kitex_gen:
	kitex -module github.com/yuanyp8/wxcommerce -type protobuf  -I ../idl  ../idl/pms/album.proto
	kitex -module github.com/yuanyp8/wxcommerce -type protobuf  -I ../idl ../idl/pms/album_pic.proto
	kitex -module github.com/yuanyp8/wxcommerce -type protobuf  -I ../idl ../idl/pms/brand.proto
	kitex -module github.com/yuanyp8/wxcommerce -type protobuf  -I ../idl ../idl/pms/comment.proto
	kitex -module github.com/yuanyp8/wxcommerce -type protobuf  -I ../idl ../idl/pms/comment_reply.proto
	kitex -module github.com/yuanyp8/wxcommerce -type protobuf  -I ../idl ../idl/pms/freight_template.proto
	kitex -module github.com/yuanyp8/wxcommerce -type protobuf  -I ../idl ../idl/pms/member_price.proto
	kitex -module github.com/yuanyp8/wxcommerce -type protobuf  -I ../idl ../idl/pms/product_attribute.proto
	kitex -module github.com/yuanyp8/wxcommerce -type protobuf  -I ../idl ../idl/pms/product_attribute_category.proto
	kitex -module github.com/yuanyp8/wxcommerce -type protobuf  -I ../idl ../idl/pms/product_attribute_value.proto
	kitex -module github.com/yuanyp8/wxcommerce -type protobuf  -I ../idl ../idl/pms/product_category.proto
	kitex -module github.com/yuanyp8/wxcommerce -type protobuf  -I ../idl ../idl/pms/product_category_attribute_relation.proto
	kitex -module github.com/yuanyp8/wxcommerce -type protobuf  -I ../idl ../idl/pms/product_full_reduction.proto
	kitex -module github.com/yuanyp8/wxcommerce -type protobuf  -I ../idl ../idl/pms/product_ladder.proto
	kitex -module github.com/yuanyp8/wxcommerce -type protobuf  -I ../idl ../idl/pms/product_operate_log.proto
	kitex -module github.com/yuanyp8/wxcommerce -type protobuf  -I ../idl ../idl/pms/product_verify_record.proto
	kitex -module github.com/yuanyp8/wxcommerce -type protobuf  -I ../idl ../idl/pms/sku_stock.proto
	kitex -module github.com/yuanyp8/wxcommerce -type protobuf  -I ../idl ../idl/pms/product.proto
	kitex -module github.com/yuanyp8/wxcommerce -type protobuf  -I ../idl ../idl/base/errno.proto


