// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: product_verify_record.proto

package product_verify_record

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseProductVerifyRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	ProductId  uint64 `protobuf:"varint,2,opt,name=ProductId,proto3" json:"ProductId,omitempty"`
	CreateTime string `protobuf:"bytes,3,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	VerifyMan  string `protobuf:"bytes,4,opt,name=VerifyMan,proto3" json:"VerifyMan,omitempty"` // 审核人
	Status     int64  `protobuf:"varint,5,opt,name=Status,proto3" json:"Status,omitempty"`
	Detail     string `protobuf:"bytes,6,opt,name=Detail,proto3" json:"Detail,omitempty"` // 反馈详情
}

func (x *BaseProductVerifyRecord) Reset() {
	*x = BaseProductVerifyRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_product_verify_record_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseProductVerifyRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseProductVerifyRecord) ProtoMessage() {}

func (x *BaseProductVerifyRecord) ProtoReflect() protoreflect.Message {
	mi := &file_product_verify_record_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseProductVerifyRecord.ProtoReflect.Descriptor instead.
func (*BaseProductVerifyRecord) Descriptor() ([]byte, []int) {
	return file_product_verify_record_proto_rawDescGZIP(), []int{0}
}

func (x *BaseProductVerifyRecord) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BaseProductVerifyRecord) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *BaseProductVerifyRecord) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *BaseProductVerifyRecord) GetVerifyMan() string {
	if x != nil {
		return x.VerifyMan
	}
	return ""
}

func (x *BaseProductVerifyRecord) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *BaseProductVerifyRecord) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type ProductVerifyRecordAddReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductVerifyRecord *BaseProductVerifyRecord `protobuf:"bytes,1,opt,name=ProductVerifyRecord,proto3" json:"ProductVerifyRecord,omitempty"`
}

func (x *ProductVerifyRecordAddReq) Reset() {
	*x = ProductVerifyRecordAddReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_product_verify_record_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductVerifyRecordAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductVerifyRecordAddReq) ProtoMessage() {}

func (x *ProductVerifyRecordAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_verify_record_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductVerifyRecordAddReq.ProtoReflect.Descriptor instead.
func (*ProductVerifyRecordAddReq) Descriptor() ([]byte, []int) {
	return file_product_verify_record_proto_rawDescGZIP(), []int{1}
}

func (x *ProductVerifyRecordAddReq) GetProductVerifyRecord() *BaseProductVerifyRecord {
	if x != nil {
		return x.ProductVerifyRecord
	}
	return nil
}

type ProductVerifyRecordAddResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pong string `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
}

func (x *ProductVerifyRecordAddResp) Reset() {
	*x = ProductVerifyRecordAddResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_product_verify_record_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductVerifyRecordAddResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductVerifyRecordAddResp) ProtoMessage() {}

func (x *ProductVerifyRecordAddResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_verify_record_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductVerifyRecordAddResp.ProtoReflect.Descriptor instead.
func (*ProductVerifyRecordAddResp) Descriptor() ([]byte, []int) {
	return file_product_verify_record_proto_rawDescGZIP(), []int{2}
}

func (x *ProductVerifyRecordAddResp) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

type ProductVerifyRecordListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Current  int64 `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`
	PageSize int64 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
}

func (x *ProductVerifyRecordListReq) Reset() {
	*x = ProductVerifyRecordListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_product_verify_record_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductVerifyRecordListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductVerifyRecordListReq) ProtoMessage() {}

func (x *ProductVerifyRecordListReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_verify_record_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductVerifyRecordListReq.ProtoReflect.Descriptor instead.
func (*ProductVerifyRecordListReq) Descriptor() ([]byte, []int) {
	return file_product_verify_record_proto_rawDescGZIP(), []int{3}
}

func (x *ProductVerifyRecordListReq) GetCurrent() int64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *ProductVerifyRecordListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ProductVerifyRecordListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64                      `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*BaseProductVerifyRecord `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ProductVerifyRecordListResp) Reset() {
	*x = ProductVerifyRecordListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_product_verify_record_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductVerifyRecordListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductVerifyRecordListResp) ProtoMessage() {}

func (x *ProductVerifyRecordListResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_verify_record_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductVerifyRecordListResp.ProtoReflect.Descriptor instead.
func (*ProductVerifyRecordListResp) Descriptor() ([]byte, []int) {
	return file_product_verify_record_proto_rawDescGZIP(), []int{4}
}

func (x *ProductVerifyRecordListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ProductVerifyRecordListResp) GetList() []*BaseProductVerifyRecord {
	if x != nil {
		return x.List
	}
	return nil
}

type ProductVerifyRecordUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductVerifyRecord *BaseProductVerifyRecord `protobuf:"bytes,1,opt,name=ProductVerifyRecord,proto3" json:"ProductVerifyRecord,omitempty"`
}

func (x *ProductVerifyRecordUpdateReq) Reset() {
	*x = ProductVerifyRecordUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_product_verify_record_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductVerifyRecordUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductVerifyRecordUpdateReq) ProtoMessage() {}

func (x *ProductVerifyRecordUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_verify_record_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductVerifyRecordUpdateReq.ProtoReflect.Descriptor instead.
func (*ProductVerifyRecordUpdateReq) Descriptor() ([]byte, []int) {
	return file_product_verify_record_proto_rawDescGZIP(), []int{5}
}

func (x *ProductVerifyRecordUpdateReq) GetProductVerifyRecord() *BaseProductVerifyRecord {
	if x != nil {
		return x.ProductVerifyRecord
	}
	return nil
}

type ProductVerifyRecordUpdateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pong string `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
}

func (x *ProductVerifyRecordUpdateResp) Reset() {
	*x = ProductVerifyRecordUpdateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_product_verify_record_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductVerifyRecordUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductVerifyRecordUpdateResp) ProtoMessage() {}

func (x *ProductVerifyRecordUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_verify_record_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductVerifyRecordUpdateResp.ProtoReflect.Descriptor instead.
func (*ProductVerifyRecordUpdateResp) Descriptor() ([]byte, []int) {
	return file_product_verify_record_proto_rawDescGZIP(), []int{6}
}

func (x *ProductVerifyRecordUpdateResp) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

type ProductVerifyRecordDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ProductVerifyRecordDeleteReq) Reset() {
	*x = ProductVerifyRecordDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_product_verify_record_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductVerifyRecordDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductVerifyRecordDeleteReq) ProtoMessage() {}

func (x *ProductVerifyRecordDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_verify_record_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductVerifyRecordDeleteReq.ProtoReflect.Descriptor instead.
func (*ProductVerifyRecordDeleteReq) Descriptor() ([]byte, []int) {
	return file_product_verify_record_proto_rawDescGZIP(), []int{7}
}

func (x *ProductVerifyRecordDeleteReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ProductVerifyRecordDeleteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pong string `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
}

func (x *ProductVerifyRecordDeleteResp) Reset() {
	*x = ProductVerifyRecordDeleteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_product_verify_record_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductVerifyRecordDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductVerifyRecordDeleteResp) ProtoMessage() {}

func (x *ProductVerifyRecordDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_verify_record_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductVerifyRecordDeleteResp.ProtoReflect.Descriptor instead.
func (*ProductVerifyRecordDeleteResp) Descriptor() ([]byte, []int) {
	return file_product_verify_record_proto_rawDescGZIP(), []int{8}
}

func (x *ProductVerifyRecordDeleteResp) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

var File_product_verify_record_proto protoreflect.FileDescriptor

var file_product_verify_record_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x70,
	0x6d, 0x73, 0x22, 0xb5, 0x01, 0x0a, 0x17, 0x42, 0x61, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x09, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4d, 0x61, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4d, 0x61, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x6b, 0x0a, 0x19, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x12, 0x4e, 0x0a, 0x13, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x52, 0x13, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x22, 0x30, 0x0a, 0x1a, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x41, 0x64,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x22, 0x52, 0x0a, 0x1a, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x65, 0x0a,
	0x1b, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x12, 0x30, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x22, 0x6e, 0x0a, 0x1c, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x4e, 0x0a, 0x13, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52,
	0x13, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x22, 0x33, 0x0a, 0x1d, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x22, 0x2e, 0x0a, 0x1c, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x33, 0x0a, 0x1d, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f,
	0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x32, 0x9d,
	0x03, 0x0a, 0x1a, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x59, 0x0a,
	0x16, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x41, 0x64, 0x64, 0x12, 0x1e, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x5c, 0x0a, 0x17, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x1f, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x20, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x62, 0x0a, 0x19, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x21, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x62, 0x0a, 0x19, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x21, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x70, 0x6d, 0x73,
	0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x42, 0x4a,
	0x5a, 0x48, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x75, 0x61,
	0x6e, 0x79, 0x70, 0x38, 0x2f, 0x77, 0x78, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2f,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x6b, 0x69, 0x74, 0x65, 0x78, 0x5f, 0x67, 0x65, 0x6e,
	0x2f, 0x70, 0x6d, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x76, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_product_verify_record_proto_rawDescOnce sync.Once
	file_product_verify_record_proto_rawDescData = file_product_verify_record_proto_rawDesc
)

func file_product_verify_record_proto_rawDescGZIP() []byte {
	file_product_verify_record_proto_rawDescOnce.Do(func() {
		file_product_verify_record_proto_rawDescData = protoimpl.X.CompressGZIP(file_product_verify_record_proto_rawDescData)
	})
	return file_product_verify_record_proto_rawDescData
}

var file_product_verify_record_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_product_verify_record_proto_goTypes = []interface{}{
	(*BaseProductVerifyRecord)(nil),       // 0: pms.BaseProductVerifyRecord
	(*ProductVerifyRecordAddReq)(nil),     // 1: pms.ProductVerifyRecordAddReq
	(*ProductVerifyRecordAddResp)(nil),    // 2: pms.ProductVerifyRecordAddResp
	(*ProductVerifyRecordListReq)(nil),    // 3: pms.ProductVerifyRecordListReq
	(*ProductVerifyRecordListResp)(nil),   // 4: pms.ProductVerifyRecordListResp
	(*ProductVerifyRecordUpdateReq)(nil),  // 5: pms.ProductVerifyRecordUpdateReq
	(*ProductVerifyRecordUpdateResp)(nil), // 6: pms.ProductVerifyRecordUpdateResp
	(*ProductVerifyRecordDeleteReq)(nil),  // 7: pms.ProductVerifyRecordDeleteReq
	(*ProductVerifyRecordDeleteResp)(nil), // 8: pms.ProductVerifyRecordDeleteResp
}
var file_product_verify_record_proto_depIdxs = []int32{
	0, // 0: pms.ProductVerifyRecordAddReq.ProductVerifyRecord:type_name -> pms.BaseProductVerifyRecord
	0, // 1: pms.ProductVerifyRecordListResp.list:type_name -> pms.BaseProductVerifyRecord
	0, // 2: pms.ProductVerifyRecordUpdateReq.ProductVerifyRecord:type_name -> pms.BaseProductVerifyRecord
	1, // 3: pms.ProductVerifyRecordService.ProductVerifyRecordAdd:input_type -> pms.ProductVerifyRecordAddReq
	3, // 4: pms.ProductVerifyRecordService.ProductVerifyRecordList:input_type -> pms.ProductVerifyRecordListReq
	5, // 5: pms.ProductVerifyRecordService.ProductVerifyRecordUpdate:input_type -> pms.ProductVerifyRecordUpdateReq
	7, // 6: pms.ProductVerifyRecordService.ProductVerifyRecordDelete:input_type -> pms.ProductVerifyRecordDeleteReq
	2, // 7: pms.ProductVerifyRecordService.ProductVerifyRecordAdd:output_type -> pms.ProductVerifyRecordAddResp
	4, // 8: pms.ProductVerifyRecordService.ProductVerifyRecordList:output_type -> pms.ProductVerifyRecordListResp
	6, // 9: pms.ProductVerifyRecordService.ProductVerifyRecordUpdate:output_type -> pms.ProductVerifyRecordUpdateResp
	8, // 10: pms.ProductVerifyRecordService.ProductVerifyRecordDelete:output_type -> pms.ProductVerifyRecordDeleteResp
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_product_verify_record_proto_init() }
func file_product_verify_record_proto_init() {
	if File_product_verify_record_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_product_verify_record_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseProductVerifyRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_product_verify_record_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductVerifyRecordAddReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_product_verify_record_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductVerifyRecordAddResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_product_verify_record_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductVerifyRecordListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_product_verify_record_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductVerifyRecordListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_product_verify_record_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductVerifyRecordUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_product_verify_record_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductVerifyRecordUpdateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_product_verify_record_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductVerifyRecordDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_product_verify_record_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductVerifyRecordDeleteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_product_verify_record_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_verify_record_proto_goTypes,
		DependencyIndexes: file_product_verify_record_proto_depIdxs,
		MessageInfos:      file_product_verify_record_proto_msgTypes,
	}.Build()
	File_product_verify_record_proto = out.File
	file_product_verify_record_proto_rawDesc = nil
	file_product_verify_record_proto_goTypes = nil
	file_product_verify_record_proto_depIdxs = nil
}

var _ context.Context

// Code generated by Kitex v0.9.0. DO NOT EDIT.

type ProductVerifyRecordService interface {
	ProductVerifyRecordAdd(ctx context.Context, req *ProductVerifyRecordAddReq) (res *ProductVerifyRecordAddResp, err error)
	ProductVerifyRecordList(ctx context.Context, req *ProductVerifyRecordListReq) (res *ProductVerifyRecordListResp, err error)
	ProductVerifyRecordUpdate(ctx context.Context, req *ProductVerifyRecordUpdateReq) (res *ProductVerifyRecordUpdateResp, err error)
	ProductVerifyRecordDelete(ctx context.Context, req *ProductVerifyRecordDeleteReq) (res *ProductVerifyRecordDeleteResp, err error)
}
