// Code generated by Kitex v0.9.0. DO NOT EDIT.

package productfullreductionservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	product_full_reduction "github.com/yuanyp8/wxcommerce/shared/kitex_gen/pms/product_full_reduction"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ProductFullReductionAdd(ctx context.Context, Req *product_full_reduction.ProductFullReductionAddReq, callOptions ...callopt.Option) (r *product_full_reduction.ProductFullReductionAddResp, err error)
	ProductFullReductionList(ctx context.Context, Req *product_full_reduction.ProductFullReductionListReq, callOptions ...callopt.Option) (r *product_full_reduction.ProductFullReductionListResp, err error)
	ProductFullReductionUpdate(ctx context.Context, Req *product_full_reduction.ProductFullReductionUpdateReq, callOptions ...callopt.Option) (r *product_full_reduction.ProductFullReductionUpdateResp, err error)
	ProductFullReductionDelete(ctx context.Context, Req *product_full_reduction.ProductFullReductionDeleteReq, callOptions ...callopt.Option) (r *product_full_reduction.ProductFullReductionDeleteResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kProductFullReductionServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kProductFullReductionServiceClient struct {
	*kClient
}

func (p *kProductFullReductionServiceClient) ProductFullReductionAdd(ctx context.Context, Req *product_full_reduction.ProductFullReductionAddReq, callOptions ...callopt.Option) (r *product_full_reduction.ProductFullReductionAddResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ProductFullReductionAdd(ctx, Req)
}

func (p *kProductFullReductionServiceClient) ProductFullReductionList(ctx context.Context, Req *product_full_reduction.ProductFullReductionListReq, callOptions ...callopt.Option) (r *product_full_reduction.ProductFullReductionListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ProductFullReductionList(ctx, Req)
}

func (p *kProductFullReductionServiceClient) ProductFullReductionUpdate(ctx context.Context, Req *product_full_reduction.ProductFullReductionUpdateReq, callOptions ...callopt.Option) (r *product_full_reduction.ProductFullReductionUpdateResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ProductFullReductionUpdate(ctx, Req)
}

func (p *kProductFullReductionServiceClient) ProductFullReductionDelete(ctx context.Context, Req *product_full_reduction.ProductFullReductionDeleteReq, callOptions ...callopt.Option) (r *product_full_reduction.ProductFullReductionDeleteResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ProductFullReductionDelete(ctx, Req)
}
