// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: product_attribute.proto

package product_attribute

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseProductAttribute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                         int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	ProductAttributeCategoryId int64  `protobuf:"varint,2,opt,name=ProductAttributeCategoryId,proto3" json:"ProductAttributeCategoryId,omitempty"`
	Name                       string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	SelectType                 int64  `protobuf:"varint,4,opt,name=SelectType,proto3" json:"SelectType,omitempty"`        // 属性选择类型：0->唯一；1->单选；2->多选
	InputType                  int64  `protobuf:"varint,5,opt,name=InputType,proto3" json:"InputType,omitempty"`          // 属性录入方式：0->手工录入；1->从列表中选取
	InputList                  string `protobuf:"bytes,6,opt,name=InputList,proto3" json:"InputList,omitempty"`           // 可选值列表，以逗号隔开
	Sort                       int64  `protobuf:"varint,7,opt,name=Sort,proto3" json:"Sort,omitempty"`                    // 排序字段：最高的可以单独上传图片
	FilterType                 int64  `protobuf:"varint,8,opt,name=FilterType,proto3" json:"FilterType,omitempty"`        // 分类筛选样式：1->普通；1->颜色
	SearchType                 int64  `protobuf:"varint,9,opt,name=SearchType,proto3" json:"SearchType,omitempty"`        // 检索类型；0->不需要进行检索；1->关键字检索；2->范围检索
	RelatedStatus              int64  `protobuf:"varint,10,opt,name=RelatedStatus,proto3" json:"RelatedStatus,omitempty"` // 相同属性产品是否关联；0->不关联；1->关联
	HandAddStatus              int64  `protobuf:"varint,11,opt,name=HandAddStatus,proto3" json:"HandAddStatus,omitempty"` // 是否支持手动新增；0->不支持；1->支持
	Type                       int64  `protobuf:"varint,12,opt,name=Type,proto3" json:"Type,omitempty"`                   // 属性的类型；0->规格；1->参数
}

func (x *BaseProductAttribute) Reset() {
	*x = BaseProductAttribute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_product_attribute_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseProductAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseProductAttribute) ProtoMessage() {}

func (x *BaseProductAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_product_attribute_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseProductAttribute.ProtoReflect.Descriptor instead.
func (*BaseProductAttribute) Descriptor() ([]byte, []int) {
	return file_product_attribute_proto_rawDescGZIP(), []int{0}
}

func (x *BaseProductAttribute) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BaseProductAttribute) GetProductAttributeCategoryId() int64 {
	if x != nil {
		return x.ProductAttributeCategoryId
	}
	return 0
}

func (x *BaseProductAttribute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaseProductAttribute) GetSelectType() int64 {
	if x != nil {
		return x.SelectType
	}
	return 0
}

func (x *BaseProductAttribute) GetInputType() int64 {
	if x != nil {
		return x.InputType
	}
	return 0
}

func (x *BaseProductAttribute) GetInputList() string {
	if x != nil {
		return x.InputList
	}
	return ""
}

func (x *BaseProductAttribute) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *BaseProductAttribute) GetFilterType() int64 {
	if x != nil {
		return x.FilterType
	}
	return 0
}

func (x *BaseProductAttribute) GetSearchType() int64 {
	if x != nil {
		return x.SearchType
	}
	return 0
}

func (x *BaseProductAttribute) GetRelatedStatus() int64 {
	if x != nil {
		return x.RelatedStatus
	}
	return 0
}

func (x *BaseProductAttribute) GetHandAddStatus() int64 {
	if x != nil {
		return x.HandAddStatus
	}
	return 0
}

func (x *BaseProductAttribute) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

type ProductAttributeAddReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductAttribute *BaseProductAttribute `protobuf:"bytes,1,opt,name=ProductAttribute,proto3" json:"ProductAttribute,omitempty"`
}

func (x *ProductAttributeAddReq) Reset() {
	*x = ProductAttributeAddReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_product_attribute_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductAttributeAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductAttributeAddReq) ProtoMessage() {}

func (x *ProductAttributeAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_attribute_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductAttributeAddReq.ProtoReflect.Descriptor instead.
func (*ProductAttributeAddReq) Descriptor() ([]byte, []int) {
	return file_product_attribute_proto_rawDescGZIP(), []int{1}
}

func (x *ProductAttributeAddReq) GetProductAttribute() *BaseProductAttribute {
	if x != nil {
		return x.ProductAttribute
	}
	return nil
}

type ProductAttributeAddResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pong string `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
}

func (x *ProductAttributeAddResp) Reset() {
	*x = ProductAttributeAddResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_product_attribute_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductAttributeAddResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductAttributeAddResp) ProtoMessage() {}

func (x *ProductAttributeAddResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_attribute_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductAttributeAddResp.ProtoReflect.Descriptor instead.
func (*ProductAttributeAddResp) Descriptor() ([]byte, []int) {
	return file_product_attribute_proto_rawDescGZIP(), []int{2}
}

func (x *ProductAttributeAddResp) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

type ProductAttributeListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Current                    int64  `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`
	PageSize                   int64  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Name                       string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Type                       int64  `protobuf:"varint,4,opt,name=Type,proto3" json:"Type,omitempty"`
	ProductAttributeCategoryId int64  `protobuf:"varint,5,opt,name=ProductAttributeCategoryId,proto3" json:"ProductAttributeCategoryId,omitempty"`
}

func (x *ProductAttributeListReq) Reset() {
	*x = ProductAttributeListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_product_attribute_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductAttributeListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductAttributeListReq) ProtoMessage() {}

func (x *ProductAttributeListReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_attribute_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductAttributeListReq.ProtoReflect.Descriptor instead.
func (*ProductAttributeListReq) Descriptor() ([]byte, []int) {
	return file_product_attribute_proto_rawDescGZIP(), []int{3}
}

func (x *ProductAttributeListReq) GetCurrent() int64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *ProductAttributeListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ProductAttributeListReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductAttributeListReq) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ProductAttributeListReq) GetProductAttributeCategoryId() int64 {
	if x != nil {
		return x.ProductAttributeCategoryId
	}
	return 0
}

type ProductAttributeListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64                   `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*BaseProductAttribute `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ProductAttributeListResp) Reset() {
	*x = ProductAttributeListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_product_attribute_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductAttributeListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductAttributeListResp) ProtoMessage() {}

func (x *ProductAttributeListResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_attribute_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductAttributeListResp.ProtoReflect.Descriptor instead.
func (*ProductAttributeListResp) Descriptor() ([]byte, []int) {
	return file_product_attribute_proto_rawDescGZIP(), []int{4}
}

func (x *ProductAttributeListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ProductAttributeListResp) GetList() []*BaseProductAttribute {
	if x != nil {
		return x.List
	}
	return nil
}

type ProductAttributeUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductAttribute *BaseProductAttribute `protobuf:"bytes,1,opt,name=ProductAttribute,proto3" json:"ProductAttribute,omitempty"`
}

func (x *ProductAttributeUpdateReq) Reset() {
	*x = ProductAttributeUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_product_attribute_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductAttributeUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductAttributeUpdateReq) ProtoMessage() {}

func (x *ProductAttributeUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_attribute_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductAttributeUpdateReq.ProtoReflect.Descriptor instead.
func (*ProductAttributeUpdateReq) Descriptor() ([]byte, []int) {
	return file_product_attribute_proto_rawDescGZIP(), []int{5}
}

func (x *ProductAttributeUpdateReq) GetProductAttribute() *BaseProductAttribute {
	if x != nil {
		return x.ProductAttribute
	}
	return nil
}

type ProductAttributeUpdateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pong string `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
}

func (x *ProductAttributeUpdateResp) Reset() {
	*x = ProductAttributeUpdateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_product_attribute_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductAttributeUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductAttributeUpdateResp) ProtoMessage() {}

func (x *ProductAttributeUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_attribute_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductAttributeUpdateResp.ProtoReflect.Descriptor instead.
func (*ProductAttributeUpdateResp) Descriptor() ([]byte, []int) {
	return file_product_attribute_proto_rawDescGZIP(), []int{6}
}

func (x *ProductAttributeUpdateResp) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

type ProductAttributeDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *ProductAttributeDeleteReq) Reset() {
	*x = ProductAttributeDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_product_attribute_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductAttributeDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductAttributeDeleteReq) ProtoMessage() {}

func (x *ProductAttributeDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_attribute_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductAttributeDeleteReq.ProtoReflect.Descriptor instead.
func (*ProductAttributeDeleteReq) Descriptor() ([]byte, []int) {
	return file_product_attribute_proto_rawDescGZIP(), []int{7}
}

func (x *ProductAttributeDeleteReq) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ProductAttributeDeleteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pong string `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
}

func (x *ProductAttributeDeleteResp) Reset() {
	*x = ProductAttributeDeleteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_product_attribute_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductAttributeDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductAttributeDeleteResp) ProtoMessage() {}

func (x *ProductAttributeDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_attribute_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductAttributeDeleteResp.ProtoReflect.Descriptor instead.
func (*ProductAttributeDeleteResp) Descriptor() ([]byte, []int) {
	return file_product_attribute_proto_rawDescGZIP(), []int{8}
}

func (x *ProductAttributeDeleteResp) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

var File_product_attribute_proto protoreflect.FileDescriptor

var file_product_attribute_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x70, 0x6d, 0x73, 0x22, 0x8a,
	0x03, 0x0a, 0x14, 0x42, 0x61, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x3e, 0x0a, 0x1a, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x1a, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x53,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x6f, 0x72, 0x74, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x53, 0x6f, 0x72, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x52,
	0x65, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0d, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x24, 0x0a, 0x0d, 0x48, 0x61, 0x6e, 0x64, 0x41, 0x64, 0x64, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x48, 0x61, 0x6e, 0x64, 0x41, 0x64,
	0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x22, 0x5f, 0x0a, 0x16, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x41,
	0x64, 0x64, 0x52, 0x65, 0x71, 0x12, 0x45, 0x0a, 0x10, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x52, 0x10, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x22, 0x2d, 0x0a, 0x17,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x22, 0xb7, 0x01, 0x0a, 0x17,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3e, 0x0a, 0x1a, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x1a, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x49, 0x64, 0x22, 0x5f, 0x0a, 0x18, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x2d, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x42, 0x61, 0x73, 0x65,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x62, 0x0a, 0x19, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x45, 0x0a, 0x10, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x70, 0x6d, 0x73, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x52, 0x10, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x22, 0x30, 0x0a, 0x1a, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x22, 0x2d, 0x0a, 0x19,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x30, 0x0a, 0x1a, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x6e,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x32, 0xf6, 0x02,
	0x0a, 0x17, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a, 0x13, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x41, 0x64, 0x64,
	0x12, 0x1b, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e,
	0x70, 0x6d, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x53, 0x0a, 0x14, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x1c, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x1d, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x59, 0x0a, 0x16, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x2e, 0x70, 0x6d, 0x73,
	0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x70, 0x6d, 0x73,
	0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x59, 0x0a, 0x16, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1e, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x42, 0x46, 0x5a, 0x44, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x75, 0x61, 0x6e, 0x79, 0x70, 0x38, 0x2f, 0x77, 0x78, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x6b,
	0x69, 0x74, 0x65, 0x78, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x70, 0x6d, 0x73, 0x2f, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_product_attribute_proto_rawDescOnce sync.Once
	file_product_attribute_proto_rawDescData = file_product_attribute_proto_rawDesc
)

func file_product_attribute_proto_rawDescGZIP() []byte {
	file_product_attribute_proto_rawDescOnce.Do(func() {
		file_product_attribute_proto_rawDescData = protoimpl.X.CompressGZIP(file_product_attribute_proto_rawDescData)
	})
	return file_product_attribute_proto_rawDescData
}

var file_product_attribute_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_product_attribute_proto_goTypes = []interface{}{
	(*BaseProductAttribute)(nil),       // 0: pms.BaseProductAttribute
	(*ProductAttributeAddReq)(nil),     // 1: pms.ProductAttributeAddReq
	(*ProductAttributeAddResp)(nil),    // 2: pms.ProductAttributeAddResp
	(*ProductAttributeListReq)(nil),    // 3: pms.ProductAttributeListReq
	(*ProductAttributeListResp)(nil),   // 4: pms.ProductAttributeListResp
	(*ProductAttributeUpdateReq)(nil),  // 5: pms.ProductAttributeUpdateReq
	(*ProductAttributeUpdateResp)(nil), // 6: pms.ProductAttributeUpdateResp
	(*ProductAttributeDeleteReq)(nil),  // 7: pms.ProductAttributeDeleteReq
	(*ProductAttributeDeleteResp)(nil), // 8: pms.ProductAttributeDeleteResp
}
var file_product_attribute_proto_depIdxs = []int32{
	0, // 0: pms.ProductAttributeAddReq.ProductAttribute:type_name -> pms.BaseProductAttribute
	0, // 1: pms.ProductAttributeListResp.list:type_name -> pms.BaseProductAttribute
	0, // 2: pms.ProductAttributeUpdateReq.ProductAttribute:type_name -> pms.BaseProductAttribute
	1, // 3: pms.ProductAttributeService.ProductAttributeAdd:input_type -> pms.ProductAttributeAddReq
	3, // 4: pms.ProductAttributeService.ProductAttributeList:input_type -> pms.ProductAttributeListReq
	5, // 5: pms.ProductAttributeService.ProductAttributeUpdate:input_type -> pms.ProductAttributeUpdateReq
	7, // 6: pms.ProductAttributeService.ProductAttributeDelete:input_type -> pms.ProductAttributeDeleteReq
	2, // 7: pms.ProductAttributeService.ProductAttributeAdd:output_type -> pms.ProductAttributeAddResp
	4, // 8: pms.ProductAttributeService.ProductAttributeList:output_type -> pms.ProductAttributeListResp
	6, // 9: pms.ProductAttributeService.ProductAttributeUpdate:output_type -> pms.ProductAttributeUpdateResp
	8, // 10: pms.ProductAttributeService.ProductAttributeDelete:output_type -> pms.ProductAttributeDeleteResp
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_product_attribute_proto_init() }
func file_product_attribute_proto_init() {
	if File_product_attribute_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_product_attribute_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseProductAttribute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_product_attribute_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductAttributeAddReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_product_attribute_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductAttributeAddResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_product_attribute_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductAttributeListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_product_attribute_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductAttributeListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_product_attribute_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductAttributeUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_product_attribute_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductAttributeUpdateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_product_attribute_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductAttributeDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_product_attribute_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductAttributeDeleteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_product_attribute_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_attribute_proto_goTypes,
		DependencyIndexes: file_product_attribute_proto_depIdxs,
		MessageInfos:      file_product_attribute_proto_msgTypes,
	}.Build()
	File_product_attribute_proto = out.File
	file_product_attribute_proto_rawDesc = nil
	file_product_attribute_proto_goTypes = nil
	file_product_attribute_proto_depIdxs = nil
}

var _ context.Context

// Code generated by Kitex v0.9.0. DO NOT EDIT.

type ProductAttributeService interface {
	ProductAttributeAdd(ctx context.Context, req *ProductAttributeAddReq) (res *ProductAttributeAddResp, err error)
	ProductAttributeList(ctx context.Context, req *ProductAttributeListReq) (res *ProductAttributeListResp, err error)
	ProductAttributeUpdate(ctx context.Context, req *ProductAttributeUpdateReq) (res *ProductAttributeUpdateResp, err error)
	ProductAttributeDelete(ctx context.Context, req *ProductAttributeDeleteReq) (res *ProductAttributeDeleteResp, err error)
}
