// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: album_pic.proto

package album_pic

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 往相册中增加图片
type AlbumPicAddReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	AlbumId uint64 `protobuf:"varint,2,opt,name=AlbumId,proto3" json:"AlbumId,omitempty"` // 相册ID
	Pic     string `protobuf:"bytes,3,opt,name=Pic,proto3" json:"Pic,omitempty"`          // 图片地址
}

func (x *AlbumPicAddReq) Reset() {
	*x = AlbumPicAddReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_album_pic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlbumPicAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlbumPicAddReq) ProtoMessage() {}

func (x *AlbumPicAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_album_pic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlbumPicAddReq.ProtoReflect.Descriptor instead.
func (*AlbumPicAddReq) Descriptor() ([]byte, []int) {
	return file_album_pic_proto_rawDescGZIP(), []int{0}
}

func (x *AlbumPicAddReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AlbumPicAddReq) GetAlbumId() uint64 {
	if x != nil {
		return x.AlbumId
	}
	return 0
}

func (x *AlbumPicAddReq) GetPic() string {
	if x != nil {
		return x.Pic
	}
	return ""
}

type AlbumPicAddResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pong string `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
}

func (x *AlbumPicAddResp) Reset() {
	*x = AlbumPicAddResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_album_pic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlbumPicAddResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlbumPicAddResp) ProtoMessage() {}

func (x *AlbumPicAddResp) ProtoReflect() protoreflect.Message {
	mi := &file_album_pic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlbumPicAddResp.ProtoReflect.Descriptor instead.
func (*AlbumPicAddResp) Descriptor() ([]byte, []int) {
	return file_album_pic_proto_rawDescGZIP(), []int{1}
}

func (x *AlbumPicAddResp) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

// 用于请求相册图片列表的信息
type AlbumPicListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Current  int64 `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`
	PageSize int64 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
}

func (x *AlbumPicListReq) Reset() {
	*x = AlbumPicListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_album_pic_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlbumPicListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlbumPicListReq) ProtoMessage() {}

func (x *AlbumPicListReq) ProtoReflect() protoreflect.Message {
	mi := &file_album_pic_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlbumPicListReq.ProtoReflect.Descriptor instead.
func (*AlbumPicListReq) Descriptor() ([]byte, []int) {
	return file_album_pic_proto_rawDescGZIP(), []int{2}
}

func (x *AlbumPicListReq) GetCurrent() int64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *AlbumPicListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type AlbumPicListData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`           // 图片id
	AlbumId uint64 `protobuf:"varint,2,opt,name=AlbumId,proto3" json:"AlbumId,omitempty"` // 相册id
	Pic     string `protobuf:"bytes,3,opt,name=Pic,proto3" json:"Pic,omitempty"`          // 图片地址
}

func (x *AlbumPicListData) Reset() {
	*x = AlbumPicListData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_album_pic_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlbumPicListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlbumPicListData) ProtoMessage() {}

func (x *AlbumPicListData) ProtoReflect() protoreflect.Message {
	mi := &file_album_pic_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlbumPicListData.ProtoReflect.Descriptor instead.
func (*AlbumPicListData) Descriptor() ([]byte, []int) {
	return file_album_pic_proto_rawDescGZIP(), []int{3}
}

func (x *AlbumPicListData) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AlbumPicListData) GetAlbumId() uint64 {
	if x != nil {
		return x.AlbumId
	}
	return 0
}

func (x *AlbumPicListData) GetPic() string {
	if x != nil {
		return x.Pic
	}
	return ""
}

type AlbumPicListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64               `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*AlbumPicListData `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *AlbumPicListResp) Reset() {
	*x = AlbumPicListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_album_pic_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlbumPicListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlbumPicListResp) ProtoMessage() {}

func (x *AlbumPicListResp) ProtoReflect() protoreflect.Message {
	mi := &file_album_pic_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlbumPicListResp.ProtoReflect.Descriptor instead.
func (*AlbumPicListResp) Descriptor() ([]byte, []int) {
	return file_album_pic_proto_rawDescGZIP(), []int{4}
}

func (x *AlbumPicListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AlbumPicListResp) GetList() []*AlbumPicListData {
	if x != nil {
		return x.List
	}
	return nil
}

// 更新具体id的图片的地址
type AlbumPicUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	AlbumId uint64 `protobuf:"varint,2,opt,name=AlbumId,proto3" json:"AlbumId,omitempty"`
	Pic     string `protobuf:"bytes,3,opt,name=Pic,proto3" json:"Pic,omitempty"`
}

func (x *AlbumPicUpdateReq) Reset() {
	*x = AlbumPicUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_album_pic_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlbumPicUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlbumPicUpdateReq) ProtoMessage() {}

func (x *AlbumPicUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_album_pic_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlbumPicUpdateReq.ProtoReflect.Descriptor instead.
func (*AlbumPicUpdateReq) Descriptor() ([]byte, []int) {
	return file_album_pic_proto_rawDescGZIP(), []int{5}
}

func (x *AlbumPicUpdateReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AlbumPicUpdateReq) GetAlbumId() uint64 {
	if x != nil {
		return x.AlbumId
	}
	return 0
}

func (x *AlbumPicUpdateReq) GetPic() string {
	if x != nil {
		return x.Pic
	}
	return ""
}

type AlbumPicUpdateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pong string `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
}

func (x *AlbumPicUpdateResp) Reset() {
	*x = AlbumPicUpdateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_album_pic_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlbumPicUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlbumPicUpdateResp) ProtoMessage() {}

func (x *AlbumPicUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_album_pic_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlbumPicUpdateResp.ProtoReflect.Descriptor instead.
func (*AlbumPicUpdateResp) Descriptor() ([]byte, []int) {
	return file_album_pic_proto_rawDescGZIP(), []int{6}
}

func (x *AlbumPicUpdateResp) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

// 根据图片id删除图片
type AlbumPicDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []uint64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *AlbumPicDeleteReq) Reset() {
	*x = AlbumPicDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_album_pic_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlbumPicDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlbumPicDeleteReq) ProtoMessage() {}

func (x *AlbumPicDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_album_pic_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlbumPicDeleteReq.ProtoReflect.Descriptor instead.
func (*AlbumPicDeleteReq) Descriptor() ([]byte, []int) {
	return file_album_pic_proto_rawDescGZIP(), []int{7}
}

func (x *AlbumPicDeleteReq) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type AlbumPicDeleteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pong string `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
}

func (x *AlbumPicDeleteResp) Reset() {
	*x = AlbumPicDeleteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_album_pic_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlbumPicDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlbumPicDeleteResp) ProtoMessage() {}

func (x *AlbumPicDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_album_pic_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlbumPicDeleteResp.ProtoReflect.Descriptor instead.
func (*AlbumPicDeleteResp) Descriptor() ([]byte, []int) {
	return file_album_pic_proto_rawDescGZIP(), []int{8}
}

func (x *AlbumPicDeleteResp) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

var File_album_pic_proto protoreflect.FileDescriptor

var file_album_pic_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x5f, 0x70, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x70, 0x6d, 0x73, 0x22, 0x4c, 0x0a, 0x0e, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x50,
	0x69, 0x63, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x6c, 0x62, 0x75,
	0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x41, 0x6c, 0x62, 0x75, 0x6d,
	0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x69, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x50, 0x69, 0x63, 0x22, 0x25, 0x0a, 0x0f, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69, 0x63,
	0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x22, 0x47, 0x0a, 0x0f, 0x41,
	0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69, 0x63, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x22, 0x4e, 0x0a, 0x10, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69, 0x63,
	0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x6c, 0x62, 0x75,
	0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x41, 0x6c, 0x62, 0x75, 0x6d,
	0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x69, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x50, 0x69, 0x63, 0x22, 0x53, 0x0a, 0x10, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69, 0x63,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x29,
	0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70,
	0x6d, 0x73, 0x2e, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69, 0x63, 0x4c, 0x69, 0x73, 0x74, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x4f, 0x0a, 0x11, 0x41, 0x6c, 0x62,
	0x75, 0x6d, 0x50, 0x69, 0x63, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x07, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x69, 0x63, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x50, 0x69, 0x63, 0x22, 0x28, 0x0a, 0x12, 0x41, 0x6c,
	0x62, 0x75, 0x6d, 0x50, 0x69, 0x63, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x70, 0x6f, 0x6e, 0x67, 0x22, 0x25, 0x0a, 0x11, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69, 0x63,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x28, 0x0a, 0x12, 0x41,
	0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69, 0x63, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x70, 0x6f, 0x6e, 0x67, 0x32, 0x8e, 0x02, 0x0a, 0x0f, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x50,
	0x69, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x41, 0x6c, 0x62,
	0x75, 0x6d, 0x50, 0x69, 0x63, 0x41, 0x64, 0x64, 0x12, 0x13, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x41,
	0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69, 0x63, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e,
	0x70, 0x6d, 0x73, 0x2e, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69, 0x63, 0x41, 0x64, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x3b, 0x0a, 0x0c, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69, 0x63, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x14, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x50,
	0x69, 0x63, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x6d, 0x73, 0x2e,
	0x41, 0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69, 0x63, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x41, 0x0a, 0x0e, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69, 0x63, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x16, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69,
	0x63, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70, 0x6d, 0x73,
	0x2e, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69, 0x63, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x41, 0x0a, 0x0e, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69, 0x63, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x70, 0x6d, 0x73, 0x2e, 0x41, 0x6c, 0x62, 0x75,
	0x6d, 0x50, 0x69, 0x63, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e,
	0x70, 0x6d, 0x73, 0x2e, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x50, 0x69, 0x63, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x75, 0x61, 0x6e, 0x79, 0x70, 0x38, 0x2f, 0x77, 0x78, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x6b,
	0x69, 0x74, 0x65, 0x78, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x70, 0x6d, 0x73, 0x2f, 0x61, 0x6c, 0x62,
	0x75, 0x6d, 0x5f, 0x70, 0x69, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_album_pic_proto_rawDescOnce sync.Once
	file_album_pic_proto_rawDescData = file_album_pic_proto_rawDesc
)

func file_album_pic_proto_rawDescGZIP() []byte {
	file_album_pic_proto_rawDescOnce.Do(func() {
		file_album_pic_proto_rawDescData = protoimpl.X.CompressGZIP(file_album_pic_proto_rawDescData)
	})
	return file_album_pic_proto_rawDescData
}

var file_album_pic_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_album_pic_proto_goTypes = []interface{}{
	(*AlbumPicAddReq)(nil),     // 0: pms.AlbumPicAddReq
	(*AlbumPicAddResp)(nil),    // 1: pms.AlbumPicAddResp
	(*AlbumPicListReq)(nil),    // 2: pms.AlbumPicListReq
	(*AlbumPicListData)(nil),   // 3: pms.AlbumPicListData
	(*AlbumPicListResp)(nil),   // 4: pms.AlbumPicListResp
	(*AlbumPicUpdateReq)(nil),  // 5: pms.AlbumPicUpdateReq
	(*AlbumPicUpdateResp)(nil), // 6: pms.AlbumPicUpdateResp
	(*AlbumPicDeleteReq)(nil),  // 7: pms.AlbumPicDeleteReq
	(*AlbumPicDeleteResp)(nil), // 8: pms.AlbumPicDeleteResp
}
var file_album_pic_proto_depIdxs = []int32{
	3, // 0: pms.AlbumPicListResp.list:type_name -> pms.AlbumPicListData
	0, // 1: pms.AlbumPicService.AlbumPicAdd:input_type -> pms.AlbumPicAddReq
	2, // 2: pms.AlbumPicService.AlbumPicList:input_type -> pms.AlbumPicListReq
	5, // 3: pms.AlbumPicService.AlbumPicUpdate:input_type -> pms.AlbumPicUpdateReq
	7, // 4: pms.AlbumPicService.AlbumPicDelete:input_type -> pms.AlbumPicDeleteReq
	1, // 5: pms.AlbumPicService.AlbumPicAdd:output_type -> pms.AlbumPicAddResp
	4, // 6: pms.AlbumPicService.AlbumPicList:output_type -> pms.AlbumPicListResp
	6, // 7: pms.AlbumPicService.AlbumPicUpdate:output_type -> pms.AlbumPicUpdateResp
	8, // 8: pms.AlbumPicService.AlbumPicDelete:output_type -> pms.AlbumPicDeleteResp
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_album_pic_proto_init() }
func file_album_pic_proto_init() {
	if File_album_pic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_album_pic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlbumPicAddReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_album_pic_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlbumPicAddResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_album_pic_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlbumPicListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_album_pic_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlbumPicListData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_album_pic_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlbumPicListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_album_pic_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlbumPicUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_album_pic_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlbumPicUpdateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_album_pic_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlbumPicDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_album_pic_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlbumPicDeleteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_album_pic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_album_pic_proto_goTypes,
		DependencyIndexes: file_album_pic_proto_depIdxs,
		MessageInfos:      file_album_pic_proto_msgTypes,
	}.Build()
	File_album_pic_proto = out.File
	file_album_pic_proto_rawDesc = nil
	file_album_pic_proto_goTypes = nil
	file_album_pic_proto_depIdxs = nil
}

var _ context.Context

// Code generated by Kitex v0.9.0. DO NOT EDIT.

type AlbumPicService interface {
	AlbumPicAdd(ctx context.Context, req *AlbumPicAddReq) (res *AlbumPicAddResp, err error)
	AlbumPicList(ctx context.Context, req *AlbumPicListReq) (res *AlbumPicListResp, err error)
	AlbumPicUpdate(ctx context.Context, req *AlbumPicUpdateReq) (res *AlbumPicUpdateResp, err error)
	AlbumPicDelete(ctx context.Context, req *AlbumPicDeleteReq) (res *AlbumPicDeleteResp, err error)
}
