CREATE TABLE pms_product (
  id BIGINT UNSIGNED PRIMARY KEY,
  brand_id BIGINT NOT NULL COMMENT '品牌id',
  product_category_id BIGINT NOT NULL COMMENT '商品分类id',
  freight_template_id BIGINT NOT NULL COMMENT '商品运费模板id',
  product_attribute_category_id BIGINT NOT NULL COMMENT '商品属性分类id',
  name varchar(64) NOT NULL COMMENT '商品名称',
  pic varchar(255) NOT NULL COMMENT '商品图片',
  product_sn varchar(64) NOT NULL COMMENT '货号',
  delete_status int(1) NOT NULL COMMENT '删除状态：0->未删除；1->已删除',
  publish_status int(1) NOT NULL COMMENT '上架状态：0->下架；1->上架',
  new_status int(1) NOT NULL COMMENT '新品状态:0->不是新品；1->新品',
  recommend_status int(1) NOT NULL COMMENT '推荐状态；0->不推荐；1->推荐',
  verify_status int(1) NOT NULL COMMENT '审核状态：0->未审核；1->审核通过',
  sort int NOT NULL COMMENT '排序',
  sale int NOT NULL COMMENT '销量',
  price decimal(10, 2) NOT NULL COMMENT '商品价格',
  promotion_price decimal(10, 2) NOT NULL COMMENT '促销价格',
  gift_growth int DEFAULT 0 NOT NULL COMMENT '赠送的成长值',
  gift_point int DEFAULT 0 NOT NULL COMMENT '赠送的积分',
  use_point_limit int NOT NULL COMMENT '限制使用的积分数',
  sub_title varchar(255) NOT NULL COMMENT '副标题',
  description text NOT NULL COMMENT '商品描述',
  original_price decimal(10, 2) NOT NULL COMMENT '市场价',
  stock int NOT NULL COMMENT '库存',
  low_stock int NOT NULL COMMENT '库存预警值',
  unit varchar(16) NOT NULL COMMENT '单位',
  weight decimal(10, 2) NOT NULL COMMENT '商品重量，默认为克',
  preview_status int(1) NOT NULL COMMENT '是否为预告商品：0->不是；1->是',
  service_ids varchar(64) NOT NULL COMMENT '以逗号分割的产品服务：1->无忧退货；2->快速退款；3->免费包邮',
  keywords varchar(255) NOT NULL COMMENT '搜索关键字',
  note varchar(255) NOT NULL COMMENT '备注',
  album_pics varchar(255) NOT NULL COMMENT '画册图片，连产品图片限制为5张，以逗号分割',
  detail_title varchar(255) NOT NULL COMMENT '详情标题',
  detail_desc text NOT NULL COMMENT '详情描述',
  detail_html text NOT NULL COMMENT '产品详情网页内容',
  detail_mobile_html text NOT NULL COMMENT '移动端网页详情',
  promotion_start_time datetime NOT NULL COMMENT '促销开始时间',
  promotion_end_time datetime NOT NULL COMMENT '促销结束时间',
  promotion_per_limit int NOT NULL COMMENT '活动限购数量',
  promotion_type int(1) NOT NULL COMMENT '促销类型：0->没有促销使用原价;1->使用促销价；2->使用会员价；3->使用阶梯价格；4->使用满减价格；5->限时购',
  brand_name varchar(255) NOT NULL COMMENT '品牌名称',
  product_category_name varchar(255) NOT NULL COMMENT '商品分类名称',
  product_category_id_Array varchar(64) NOT NULL COMMENT '商品分类id字符串'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商品信息' ROW_FORMAT=DYNAMIC;
