// Code generated by Kitex v0.9.0. DO NOT EDIT.

package brandservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	brand "github.com/yuanyp8/wxcommerce/shared/kitex_gen/pms/brand"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	BrandAdd(ctx context.Context, Req *brand.BrandAddReq, callOptions ...callopt.Option) (r *brand.BrandAddResp, err error)
	BrandList(ctx context.Context, Req *brand.BrandListReq, callOptions ...callopt.Option) (r *brand.BrandListResp, err error)
	BrandListByIds(ctx context.Context, Req *brand.BrandListByIdsReq, callOptions ...callopt.Option) (r *brand.BrandListResp, err error)
	BrandUpdate(ctx context.Context, Req *brand.BrandUpdateReq, callOptions ...callopt.Option) (r *brand.BrandUpdateResp, err error)
	BrandDelete(ctx context.Context, Req *brand.BrandDeleteReq, callOptions ...callopt.Option) (r *brand.BrandDeleteResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kBrandServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kBrandServiceClient struct {
	*kClient
}

func (p *kBrandServiceClient) BrandAdd(ctx context.Context, Req *brand.BrandAddReq, callOptions ...callopt.Option) (r *brand.BrandAddResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BrandAdd(ctx, Req)
}

func (p *kBrandServiceClient) BrandList(ctx context.Context, Req *brand.BrandListReq, callOptions ...callopt.Option) (r *brand.BrandListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BrandList(ctx, Req)
}

func (p *kBrandServiceClient) BrandListByIds(ctx context.Context, Req *brand.BrandListByIdsReq, callOptions ...callopt.Option) (r *brand.BrandListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BrandListByIds(ctx, Req)
}

func (p *kBrandServiceClient) BrandUpdate(ctx context.Context, Req *brand.BrandUpdateReq, callOptions ...callopt.Option) (r *brand.BrandUpdateResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BrandUpdate(ctx, Req)
}

func (p *kBrandServiceClient) BrandDelete(ctx context.Context, Req *brand.BrandDeleteReq, callOptions ...callopt.Option) (r *brand.BrandDeleteResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BrandDelete(ctx, Req)
}
