.PHONY: kitex_gen_service
kitex_gen_service:
	kitex -module github.com/yuanyp8/wxcommerce -use github.com/yuanyp8/wxcommerce/shared/kitex_gen -service pms.AlbumService -type protobuf  -I ../../idl/pms  ../../idl/pms/album.proto
	kitex -module github.com/yuanyp8/wxcommerce -use github.com/yuanyp8/wxcommerce/shared/kitex_gen -service pms.AlbumPicService -type protobuf  -I ../../idl/pms  ../../idl/pms/album_pic.proto
	kitex -module github.com/yuanyp8/wxcommerce -use github.com/yuanyp8/wxcommerce/shared/kitex_gen -service pms.BrandService -type protobuf  -I ../../idl/pms  ../../idl/pms/brand.proto
	kitex -module github.com/yuanyp8/wxcommerce -use github.com/yuanyp8/wxcommerce/shared/kitex_gen -service pms.CommentService -type protobuf  -I ../../idl/pms  ../../idl/pms/comment.proto
	kitex -module github.com/yuanyp8/wxcommerce -use github.com/yuanyp8/wxcommerce/shared/kitex_gen -service pms.CommentReplyService -type protobuf  -I ../../idl/pms  ../../idl/pms/comment_reply.proto
	kitex -module github.com/yuanyp8/wxcommerce -use github.com/yuanyp8/wxcommerce/shared/kitex_gen -service pms.FreightTemplateService -type protobuf  -I ../../idl/pms  ../../idl/pms/freight_template.proto
	kitex -module github.com/yuanyp8/wxcommerce -use github.com/yuanyp8/wxcommerce/shared/kitex_gen -service pms.MemberPriceService -type protobuf  -I ../../idl/pms  ../../idl/pms/member_price.proto
	kitex -module github.com/yuanyp8/wxcommerce -use github.com/yuanyp8/wxcommerce/shared/kitex_gen -service pms.ProductAttributeService -type protobuf  -I ../../idl/pms  ../../idl/pms/product_attribute.proto
	kitex -module github.com/yuanyp8/wxcommerce -use github.com/yuanyp8/wxcommerce/shared/kitex_gen -service pms.ProductAttributeCategoryService -type protobuf  -I ../../idl/pms  ../../idl/pms/product_attribute_category.proto
	kitex -module github.com/yuanyp8/wxcommerce -use github.com/yuanyp8/wxcommerce/shared/kitex_gen -service pms.ProductAttributeValueService -type protobuf  -I ../../idl/pms  ../../idl/pms/product_attribute_value.proto
	kitex -module github.com/yuanyp8/wxcommerce -use github.com/yuanyp8/wxcommerce/shared/kitex_gen -service pms.ProductCategoryService -type protobuf  -I ../../idl/pms  ../../idl/pms/product_category.proto
	kitex -module github.com/yuanyp8/wxcommerce -use github.com/yuanyp8/wxcommerce/shared/kitex_gen -service pms.ProductCategoryAttributeRelationService -type protobuf  -I ../../idl/pms  ../../idl/pms/product_category_attribute_relation.proto
	kitex -module github.com/yuanyp8/wxcommerce -use github.com/yuanyp8/wxcommerce/shared/kitex_gen -service pms.ProductFullReductionService -type protobuf  -I ../../idl/pms  ../../idl/pms/product_full_reduction.proto
	kitex -module github.com/yuanyp8/wxcommerce -use github.com/yuanyp8/wxcommerce/shared/kitex_gen -service pms.ProductLadderService -type protobuf  -I ../../idl/pms  ../../idl/pms/product_ladder.proto
	kitex -module github.com/yuanyp8/wxcommerce -use github.com/yuanyp8/wxcommerce/shared/kitex_gen -service pms.ProductOperateLogService -type protobuf  -I ../../idl/pms  ../../idl/pms/product_operate_log.proto
	kitex -module github.com/yuanyp8/wxcommerce -use github.com/yuanyp8/wxcommerce/shared/kitex_gen -service pms.ProductService -type protobuf  -I ../../idl/pms  ../../idl/pms/product.proto
	kitex -module github.com/yuanyp8/wxcommerce -use github.com/yuanyp8/wxcommerce/shared/kitex_gen -service pms.ProductVerifyRecordService -type protobuf  -I ../../idl/pms  ../../idl/pms/product_verify_record.proto
	kitex -module github.com/yuanyp8/wxcommerce -use github.com/yuanyp8/wxcommerce/shared/kitex_gen -service pms.SkuStockService -type protobuf  -I ../../idl/pms  ../../idl/pms/sku_stock.proto
	rm build.sh
	rm -rf script