// Code generated by Kitex v0.9.0. DO NOT EDIT.

package commentreplayservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	comment_reply "github.com/yuanyp8/wxcommerce/shared/kitex_gen/pms/comment_reply"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CommentReplayAdd(ctx context.Context, Req *comment_reply.CommentReplayAddReq, callOptions ...callopt.Option) (r *comment_reply.CommentReplayAddResp, err error)
	CommentReplayList(ctx context.Context, Req *comment_reply.CommentReplayListReq, callOptions ...callopt.Option) (r *comment_reply.CommentReplayListResp, err error)
	CommentReplayUpdate(ctx context.Context, Req *comment_reply.CommentReplayUpdateReq, callOptions ...callopt.Option) (r *comment_reply.CommentReplayUpdateResp, err error)
	CommentReplayDelete(ctx context.Context, Req *comment_reply.CommentReplayDeleteReq, callOptions ...callopt.Option) (r *comment_reply.CommentReplayDeleteResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kCommentReplayServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCommentReplayServiceClient struct {
	*kClient
}

func (p *kCommentReplayServiceClient) CommentReplayAdd(ctx context.Context, Req *comment_reply.CommentReplayAddReq, callOptions ...callopt.Option) (r *comment_reply.CommentReplayAddResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommentReplayAdd(ctx, Req)
}

func (p *kCommentReplayServiceClient) CommentReplayList(ctx context.Context, Req *comment_reply.CommentReplayListReq, callOptions ...callopt.Option) (r *comment_reply.CommentReplayListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommentReplayList(ctx, Req)
}

func (p *kCommentReplayServiceClient) CommentReplayUpdate(ctx context.Context, Req *comment_reply.CommentReplayUpdateReq, callOptions ...callopt.Option) (r *comment_reply.CommentReplayUpdateResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommentReplayUpdate(ctx, Req)
}

func (p *kCommentReplayServiceClient) CommentReplayDelete(ctx context.Context, Req *comment_reply.CommentReplayDeleteReq, callOptions ...callopt.Option) (r *comment_reply.CommentReplayDeleteResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommentReplayDelete(ctx, Req)
}
